language: go
go:
- 1.5
- 1.6
- 1.7
- 1.8

before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}

script:
- go test -v -p=1 -race -timeout=120s github.com/discord/zorkian-kafka/...
- go vet github.com/discord/zorkian-kafka/...
- go test -bench '.*' -run none github.com/discord/zorkian-kafka/...

env:
- WITH_INTEGRATION=false GOMAXPROCS=4

sudo: false
